### ISSUE TITLE
no "Bitgen.exe" application 

### ISSUE THREAD

**Issue by BigGod12** [Lyopx/FLASH-BTC-USDT#1]
there is no "Bitgen.exe" application.. how to generate the coin after running Bitgen Activator Exe, which is the only exe file avail in the project, wonder how those that start and fork the repo got it working......

**Comment by Lyopx** [comment]
> there is no "Bitgen.exe" application.. how to generate the coin after running Bitgen Activator Exe, which is the only exe file avail in the project, wonder how those that start and fork the repo got it working......

If you want to use this free version for a fee, you can contact me via telegram.
tg: t.me/floxier

You can also try to download it from the "Relase" section.
